"""Triage: which parts of a large change deserve a reviewer's attention. Deterministic, no model calls.

Every hunk is `trivial` when it cannot change behaviour:
  whitespace  only layout changed (also re-wrapped lines and trailing commas)
  comment     only comments or docstrings changed
  imports     import lines reordered
  rename      one identifier replaced by another, the same substitution repeated across the change
  version     the project's own version number bumped
and whole files are trivial when they are docs, generated content, or a move without edits.
A file with a non-trivial hunk is `risky` when its changed lines touch auth, money, concurrency,
persistence or error handling, delete a check, or change a public signature (from the symbol graph),
else `normal`. Trivial hunks are left out of a split review (see units.py); risk orders the size
budget and is shown to the reviewers of a split review.
"""

import keyword
import posixpath
import re
from collections import Counter
from dataclasses import dataclass, field, replace
from typing import Literal

from nitless.context.changes import changed_file
from nitless.context.index import RepoIndex, is_test_file
from nitless.context.symbols import language_of
from nitless.diff import DiffLine, FileDiff, Hunk

Level = Literal["trivial", "normal", "risky"]

DOC_EXTS = {".md", ".markdown", ".rst", ".adoc"}
DOC_NAMES = {"changelog", "license", "licence", "authors", "contributors", "notice", "readme"}
GENERATED_RE = re.compile(r"(^|/)(__snapshots__|generated|__generated__)/|\.(snap|lock)$|[._-]generated\.|\.min\."
                          r"|_pb2(_grpc)?\.py$|\.pb\.go$|\.g\.dart$|\.designer\.cs$|(^|/)package-lock\.json$")
GENERATED_MARK_RE = re.compile(r"@generated|do not edit|auto-?generated|generated by", re.I)
VERSION_FILES = {"package.json", "pyproject.toml", "setup.cfg", "setup.py", "version.txt", "VERSION", "Chart.yaml",
                 "__init__.py", "_version.py", "version.py", "gradle.properties"}
VERSION_LINE_RE = re.compile(r"""^\s*("version"\s*:|version\s*[=:]|__version__\s*=|appVersion\s*:)\s*["']?[\w.+-]+""")
COMMENT_RE = {
    "python": re.compile(r"^\s*#"),
    "c": re.compile(r"^\s*(//|/\*|\*|\*/)"),
    "markup": re.compile(r"^\s*(<!--|-->)"),
}
IMPORT_RE = re.compile(r"^\s*(import\s|from\s+\S+\s+import\s|export\s+\*?\s*\{?.*\bfrom\s)")
TOKEN_RE = re.compile(r"[A-Za-z_$][\w$]*|\d[\w.]*|\S")
IDENT_RE = re.compile(r"[A-Za-z_$][\w$]*")
NOT_RENAMES = {*keyword.kwlist, "true", "false", "null", "undefined", "this", "self", "super", "new", "var", "let",
               "const", "function", "public", "private", "protected", "static", "final", "void", "instanceof",
               "typeof", "extends", "implements", "throws", "readonly", "async", "await", "abstract"}
MIN_RENAME_REPEATS = 3  # a substitution seen fewer times is more likely a real edit than a mechanical rename
TRAILING_COMMA_RE = re.compile(r",(?=[)\]}])")

RISK_PATH_RE = re.compile(r"auth|login|permission|acl|secur|crypt|secret|token|session|password|payment|billing"
                          r"|invoice|refund|money|wallet|ledger|migrat|transaction")
RISK_LINE_RES = {
    "auth/permissions": re.compile(r"\b(authori[sz]\w*|authenticat\w*|permission\w*|is_?admin|role\w*|owner\w*|"
                                   r"csrf|jwt|password\w*|secret\w*|api_?key|hmac|signature)\b", re.I),
    "money": re.compile(r"\b(\w*cents|amount\w*|price\w*|refund\w*|balance|currency|charge\w*|payment\w*|"
                        r"basis_?points|bps)\b", re.I),
    "concurrency/transactions": re.compile(r"\b(lock\w*|mutex|synchronized|transaction\w*|rollback|commit|"
                                           r"for update|atomic\w*|semaphore|isolation|@Transactional)\b", re.I),
    "persistence/migrations": re.compile(r"\b(migration|alter table|drop table|create table|add_column|"
                                         r"drop_column|@Entity|@Column|UniqueConstraint|ForeignKey|flush)\b", re.I),
    "dangerous call": re.compile(r"\b(eval|exec|os\.system|subprocess\.\w+|pickle\.loads?|yaml\.load|"
                                 r"innerHTML|dangerouslySetInnerHTML|Runtime\.getRuntime)\b"),
}
CHECK_RE = re.compile(r"^\s*(if|elif|else if|assert|raise|throw|require|except|catch|guard)\b|\b(validate\w*|check\w*|"
                      r"ensure\w*)\s*\(|@(Valid|NotNull|NotBlank|Size|Min|Max|Pattern|Positive)\b|\bthrow\b|\braise\b")


@dataclass
class FileTriage:
    path: str
    level: Level
    reasons: list[str] = field(default_factory=list)  # risky: why; trivial: what kind of change
    trivial_hunks: dict[int, str] = field(default_factory=dict)  # hunk index -> kind


@dataclass
class Triage:
    files: dict[str, FileTriage]
    renames: set[tuple[str, str]] = field(default_factory=set)  # mechanical (old, new) identifier renames

    def level(self, path: str) -> Level:
        return self.files[path].level if path in self.files else "normal"

    def reviewable(self, diffs: list[FileDiff]) -> list[FileDiff]:
        """The diffs without their trivial hunks; files left with nothing to review are dropped."""
        out = []
        for f in diffs:
            t = self.files.get(f.path)
            if t is None or (t.level != "trivial" and not t.trivial_hunks):
                out.append(f)
            elif t.level != "trivial":
                out.append(replace(f, hunks=[h for i, h in enumerate(f.hunks) if i not in t.trivial_hunks]))
        return out

    def omitted(self) -> Counter[str]:
        """Trivial hunks by kind (a trivial file counts once per kind)."""
        counts: Counter[str] = Counter()
        for t in self.files.values():
            if t.level == "trivial" and not t.trivial_hunks:
                counts.update(t.reasons)
            else:
                counts.update(t.trivial_hunks.values())
        return counts

    def trace(self) -> dict:
        levels = Counter(t.level for t in self.files.values())
        return {"levels": dict(levels), "omitted_hunks": dict(self.omitted()),
                "files": [{"path": t.path, "level": t.level, "reasons": t.reasons,
                           "trivial_hunks": len(t.trivial_hunks)} for t in self.files.values()]}


def triage(diffs: list[FileDiff], index: RepoIndex | None = None) -> Triage:
    """Classify every changed file and hunk. With an index, signature changes of public symbols count as risk."""
    renames = _repeated_renames(diffs)
    breaking = _breaking_symbols(diffs, index) if index is not None else {}
    files = {f.path: _classify(f, renames, breaking.get(f.path, [])) for f in diffs}
    used = {pair for f in diffs for i, h in enumerate(f.hunks) if files[f.path].trivial_hunks.get(i) == "rename"
            for pair in substitutions(*_sides(h))}
    return Triage(files, used)


def _classify(f: FileDiff, renames: set[tuple[str, str]], breaking: list[str]) -> FileTriage:
    kind = _trivial_file(f)
    if kind:
        return FileTriage(f.path, "trivial", [kind])
    trivial = {i: k for i, h in enumerate(f.hunks) if (k := trivial_hunk(f.path, h, renames))}
    if f.hunks and len(trivial) == len(f.hunks):
        return FileTriage(f.path, "trivial", sorted(set(trivial.values())), trivial)
    lines = [ln for i, h in enumerate(f.hunks) if i not in trivial for ln in h.lines if ln.kind != " "]
    reasons = [] if is_test_file(f.path) else _risks(f.path, lines, breaking)
    return FileTriage(f.path, "risky" if reasons else "normal", reasons, trivial)


def _trivial_file(f: FileDiff) -> str | None:
    name = posixpath.basename(f.path)
    stem, ext = posixpath.splitext(name)
    if f.status == "renamed" and not f.hunks:
        return "moved"
    if f.status == "deleted":
        return None
    in_docs_dir = f.path.startswith(("docs/", "doc/")) and language_of(f.path) is None
    if ext.lower() in DOC_EXTS or stem.lower() in DOC_NAMES or in_docs_dir:
        return "docs"
    first_added = [ln.text for h in f.hunks[:1] for ln in h.lines[:8] if ln.kind == "+"]
    if GENERATED_RE.search(f.path) or (f.status == "added" and any(GENERATED_MARK_RE.search(t) for t in first_added)):
        return "generated"
    return None


def _sides(h: Hunk) -> tuple[list[str], list[str]]:
    """The removed and the added lines of a hunk."""
    return [ln.text for ln in h.lines if ln.kind == "-"], [ln.text for ln in h.lines if ln.kind == "+"]


def trivial_hunk(path: str, h: Hunk, renames: set[tuple[str, str]] = frozenset()) -> str | None:
    removed, added = _sides(h)
    if _squash(removed) == _squash(added):
        return "whitespace"
    changed = [t for t in removed + added if t.strip()]
    if _all_comments(path, h):
        return "comment"
    if all(IMPORT_RE.match(t) for t in changed) and Counter(_tokens(removed)) == Counter(_tokens(added)):
        return "imports"
    if posixpath.basename(path) in VERSION_FILES and removed and all(VERSION_LINE_RE.match(t) for t in changed):
        return "version"
    pairs = substitutions(removed, added)
    if pairs and pairs <= renames:
        return "rename"
    return None


def _squash(lines: list[str]) -> str:
    return TRAILING_COMMA_RE.sub("", re.sub(r"\s+", "", "".join(lines)))


def _tokens(lines: list[str]) -> list[str]:
    return [t for line in lines for t in TOKEN_RE.findall(line)]


def _all_comments(path: str, h: Hunk) -> bool:
    """Every changed non-blank line is a comment, or sits inside a docstring (tracked through the hunk)."""
    language = language_of(path)
    style = "python" if language == "python" else "c" if language else "markup" if path.endswith((".html", ".xml")) \
        else None
    if style is None:
        return False
    in_doc, changed = False, False
    for ln in h.lines:
        text = ln.text.strip()
        quotes = text.count('"""') + text.count("'''") if style == "python" else 0
        is_doc = in_doc or quotes > 0
        in_doc = in_doc != (quotes % 2 == 1)
        if ln.kind == " " or not text:
            continue
        changed = True
        if not (is_doc or COMMENT_RE[style].match(text)):
            return False
    return changed


def substitutions(removed: list[str], added: list[str]) -> set[tuple[str, str]]:
    """{(old, new)} identifier pairs when `added` is `removed` with identifiers replaced one-for-one, else empty."""
    old, new = _tokens(removed), _tokens(added)
    if len(old) != len(new) or old == new:
        return set()
    pairs = {(a, b) for a, b in zip(old, new, strict=True) if a != b}
    if not all(IDENT_RE.fullmatch(t) and t not in NOT_RENAMES for pair in pairs for t in pair):
        return set()
    return pairs if len({a for a, _ in pairs}) == len(pairs) else set()  # each old name maps to one new name


def _repeated_renames(diffs: list[FileDiff]) -> set[tuple[str, str]]:
    """Substitutions that recur across the change, i.e. a mechanical rename rather than an edit."""
    seen: Counter[tuple[str, str]] = Counter()
    for f in diffs:
        for h in f.hunks:
            seen.update(substitutions(*_sides(h)))
    return {pair for pair, n in seen.items() if n >= MIN_RENAME_REPEATS}


def _breaking_symbols(diffs: list[FileDiff], index: RepoIndex) -> dict[str, list[str]]:
    olds = index.base_sources([f.old_path for f in diffs if f.old_path and f.status in ("modified", "renamed")])
    out: dict[str, list[str]] = {}
    for f in diffs:
        if f.status not in ("modified", "renamed") or f.old_path not in olds:
            continue
        ch = changed_file(f, index.source(f.path), olds[f.old_path])
        names = [s.definition.qualname for s in ch.symbols if s.breaking and not s.definition.name.startswith("_")]
        if names:
            out[f.path] = names
    return out


def _risks(path: str, lines: list[DiffLine], breaking: list[str]) -> list[str]:
    reasons = []
    if RISK_PATH_RE.search(path.lower()):
        reasons.append("sensitive path")
    text = "\n".join(ln.text for ln in lines)
    reasons += [name for name, pattern in RISK_LINE_RES.items() if pattern.search(text)]
    added = {_squash([ln.text]) for ln in lines if ln.kind == "+"}
    if any(CHECK_RE.search(ln.text) and _squash([ln.text]) not in added for ln in lines if ln.kind == "-"):
        reasons.append("removes a check or error handling")
    if breaking:
        reasons.append("changes the signature of " + ", ".join(breaking[:3]))
    return reasons
